p = (input('Digite algo: '))
print('A variável ', p, ' é alfabética? ', (p.isalpha()))
print('A variável ', p, ' é numérica? ', (p.isnumeric()))
print('A variável ', p, ' é alfanumérica? ', (p.isalnum()))
print('A variável ', p, ' é dígito? ', (p.isdigit()))
print('A variável ', p, ' é minúscula? ', (p.islower()))
print('A variável ', p, ' é maíuscula? ', (p.isupper()))
print('A variável ', p, ' é um espaço? ', (p.isspace()))
print('A variável ', p, ' é ASCII? ', (p.isascii()))
print('A variável ', p, ' é decimal? ', (p.isdecimal()))
print('A variável ', p, ' é identificador? ', (p.isidentifier()))
print('A variável ', p, ' é imprimível? ', (p.isprintable()))